name: seedperturbation
description: TODO
keywords:
  - TODO
tools:
  - seedperturbation:
      description: TODO
      homepage: TODO
      documentation: TODO
      licence:
        - TODO
input:
  - - meta:
        type: map
        description: Groovy Map containing sample information
    - seeds:
        type: file
        description: TODO
output:
  perturbed_seeds:
    - meta:
        type: map
        description: Groovy Map containing sample information
    - ${meta.seeds_id}.*.${seeds.extension}:
        type: file
        description: TODO
        pattern: ${meta.seeds_id}.*.${seeds.extension}
  versions:
    - versions.yml:
        type: file
        description: TODO
        pattern: versions.yml
authors:
  - "@TODO"
maintainers:
  - "@TODO"
