name: shortest_paths
description: TODO
keywords:
  - TODO
tools:
  - shortest_paths:
      description: TODO
      homepage: TODO
      documentation: TODO
      licence:
        - TODO
input:
  - - meta:
        type: map
        description: Groovy Map containing sample information
    - network:
        type: file
        description: TODO
output:
  sp:
    - meta:
        type: map
        description: Groovy Map containing sample information
    - ${meta.id}.shortest_paths.pkl:
        type: file
        description: TODO
        pattern: ${meta.id}.shortest_paths.pkl
  versions:
    - versions.yml:
        type: file
        description: TODO
        pattern: versions.yml
authors:
  - "@TODO"
maintainers:
  - "@TODO"
