name: proximity
description: TODO
keywords:
  - TODO
tools:
  - proximity:
      description: TODO
      homepage: TODO
      documentation: TODO
      licence:
        - TODO
input:
  - - network:
        type: file
        description: TODO
  - - shortest_paths:
        type: file
        description: TODO
  - - drug_to_target:
        type: file
        description: TODO
  - - meta:
        type: map
        description: Groovy Map containing sample information
    - module:
        type: file
        description: TODO
output:
  proxout:
    - ${meta.id}.proximity.tsv:
        type: file
        description: TODO
        pattern: ${meta.id}.proximity.tsv
  versions:
    - versions.yml:
        type: file
        description: TODO
        pattern: versions.yml
authors:
  - "@TODO"
maintainers:
  - "@TODO"
